apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        name: cassandra-volume-claim
    name: cassandra-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 10Mi

