apiVersion: v1
kind: Service
metadata:
    labels:
        name: cassandra-headless-service
    name: cassandra-headless-service
spec:
    clusterIP: None
    ports:
        - port: 7000
          name: intra-node-communication
        - port: 7001
          name: tls-intra-node-communication
    selector:
        name: cassandra

