apiVersion: v1
kind: Service
metadata:
    labels:
        name: cassandra
    name: cassandra
spec:
    ports:
        - port: 9042
          name: cql-native
        - port: 9160
          name: thrift-clients
        - port: 7199
          name: jmx
    selector:
        name: cassandra

